-- AUDITA — I3 Catálogo de serviços e situação de liberação
-- Fonte: AUDDOC004 Rev.00 e AUDDOC005 Rev.00; unidade de cobrança de referência: AUDDOC011 §6.
-- Nenhum serviço é liberado por esta migração: todos iniciam "Não liberado", como na AUDDOC004.

create table audita.services (
  id                        uuid primary key default gen_random_uuid(),
  service_code              text not null unique check (service_code ~ '^[A-Z]{3}-[A-Z0-9-]{2,12}$'),
  kind                      text not null check (kind in ('servico', 'oferta')),
  parent_id                 uuid references audita.services (id) on delete restrict,
  name                      text not null check (length(btrim(name)) between 3 and 200),
  family                    text not null check (length(btrim(family)) between 3 and 60),
  norm                      text,
  grouping                  text,
  matrix_class              text not null check (matrix_class in ('A', 'B', 'C')),
  matrix_class_label        text not null,
  priority                  text check (priority is null or priority in ('Alta', 'Média', 'Futura')),
  scope_preliminary         text,
  scope_limits              text,
  tst_compatibility         text,
  modality                  text,
  evidence_required         text,
  technical_responsibility  text,
  legal_reference           text,
  official_url              text check (official_url is null or official_url ~ '^https://'),
  docs_received             text not null default 'nao' check (docs_received in ('nao', 'parcial', 'sim')),
  rt_confirmed              text not null default 'nao' check (rt_confirmed in ('nao', 'parcial', 'sim', 'nao_aplicavel')),
  resources_confirmed       text not null default 'nao' check (resources_confirmed in ('nao', 'parcial', 'sim', 'nao_aplicavel')),
  audita_notes              text,
  commercial_status         text not null default 'nao_liberado'
                              check (commercial_status in ('nao_liberado', 'apto_tecnicamente', 'apto_comercialmente', 'expansao_futura')),
  status_basis              text not null,
  status_reference          text,
  status_decided_at         timestamptz not null default now(),
  status_decided_by         uuid,
  pricing_model             text not null default 'hora_tecnica' check (pricing_model in ('hora_tecnica', 'sem_modelo_definido')),
  billing_unit_ref          text,
  catalog_status            text not null default 'ativo' check (catalog_status in ('ativo', 'inativo')),
  source_reference          text not null default 'AUDDOC004 Rev.00 / AUDDOC005 Rev.00',
  created_at                timestamptz not null default now(),
  created_by                uuid default auth.uid(),
  updated_at                timestamptz not null default now(),
  updated_by                uuid,
  constraint services_offer_has_parent check (kind = 'servico' or parent_id is not null)
);
comment on table audita.services is 'Catálogo de serviços (AUDDOC004/005). Proposta comercial final somente para situação "apto_comercialmente".';
comment on column audita.services.commercial_status is 'AUDDOC005 §14: nao_liberado | apto_tecnicamente | apto_comercialmente | expansao_futura.';
comment on column audita.services.pricing_model is 'hora_tecnica = metodologia AUDDOC011; sem_modelo_definido = sem cálculo automático (ex.: assinatura SaaS, AUDDOC011 §6).';
create index services_family_idx on audita.services (family, service_code);
create index services_status_idx on audita.services (commercial_status);

create table audita.service_status_history (
  id            bigint generated always as identity primary key,
  service_id    uuid not null references audita.services (id) on delete restrict,
  from_status   text,
  to_status     text not null,
  basis         text not null,
  reference     text,
  decided_at    timestamptz not null default now(),
  decided_by    uuid
);
create index service_status_history_service_idx on audita.service_status_history (service_id, decided_at desc);
comment on table audita.service_status_history is 'Trilha das decisões de situação comercial por serviço: de/para, fundamento, referência, data e responsável.';

create trigger service_status_history_immutable
  before update or delete on audita.service_status_history
  for each row execute function audita.audit_log_block_changes();

create or replace function audita.services_before_write()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if tg_op = 'INSERT' then
    new.created_at := now();
    new.created_by := (select auth.uid());
    new.status_decided_at := now();
    new.status_decided_by := (select auth.uid());
    return new;
  end if;

  if new.id is distinct from old.id or new.service_code is distinct from old.service_code
     or new.kind is distinct from old.kind or new.parent_id is distinct from old.parent_id
     or new.created_at is distinct from old.created_at or new.created_by is distinct from old.created_by then
    raise exception 'Código, tipo e vínculo do serviço são permanentes' using errcode = '42501';
  end if;

  if new.commercial_status is distinct from old.commercial_status then
    if new.status_basis is not distinct from old.status_basis or length(btrim(coalesce(new.status_basis, ''))) < 10 then
      raise exception 'Informe o fundamento da decisão (mínimo de 10 caracteres)' using errcode = '23514';
    end if;
    if new.commercial_status = 'apto_comercialmente' and old.catalog_status = 'inativo' then
      raise exception 'Serviço inativo no catálogo não pode ser liberado' using errcode = '23514';
    end if;
    new.status_decided_at := now();
    new.status_decided_by := (select auth.uid());
  elsif new.status_basis is distinct from old.status_basis
     or new.status_reference is distinct from old.status_reference
     or new.status_decided_at is distinct from old.status_decided_at
     or new.status_decided_by is distinct from old.status_decided_by then
    raise exception 'O fundamento só pode ser registrado junto com uma mudança de situação' using errcode = '42501';
  end if;
  return new;
end;
$$;

create trigger services_before_write
  before insert or update on audita.services
  for each row execute function audita.services_before_write();
create trigger services_set_updated_meta
  before update on audita.services
  for each row execute function audita.set_updated_meta();
create trigger services_audit
  after insert or update or delete on audita.services
  for each row execute function audita.log_row_change('id', 'id');

create or replace function audita.services_status_history()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if tg_op = 'INSERT' or new.commercial_status is distinct from old.commercial_status then
    insert into audita.service_status_history (service_id, from_status, to_status, basis, reference, decided_at, decided_by)
    values (new.id, case when tg_op = 'UPDATE' then old.commercial_status end, new.commercial_status,
            new.status_basis, new.status_reference, new.status_decided_at, new.status_decided_by);
  end if;
  return new;
end;
$$;

create trigger services_status_history
  after insert or update on audita.services
  for each row execute function audita.services_status_history();

create or replace function audita.service_allows_commercial_proposal(p_service_id uuid)
returns boolean
language sql
stable
security invoker
set search_path = ''
as $$
  select coalesce((
    select s.commercial_status = 'apto_comercialmente' and s.catalog_status = 'ativo'
    from audita.services s where s.id = p_service_id
  ), false);
$$;

alter table audita.services enable row level security;
alter table audita.service_status_history enable row level security;

create policy services_select on audita.services for select to authenticated using ((select audita.is_admin()));
create policy services_update on audita.services for update to authenticated
  using ((select audita.is_admin())) with check ((select audita.is_admin()));
create policy service_status_history_select on audita.service_status_history for select to authenticated using ((select audita.is_admin()));

revoke all on audita.services, audita.service_status_history from public, anon, authenticated;
grant select, update on audita.services to authenticated;
grant select on audita.service_status_history to authenticated;

revoke all on function audita.services_before_write(), audita.services_status_history(),
  audita.service_allows_commercial_proposal(uuid) from public, anon, authenticated;
grant execute on function audita.service_allows_commercial_proposal(uuid) to authenticated;

grant all on all tables in schema audita to service_role;
grant all on all functions in schema audita to service_role;

insert into audita.services (service_code, kind, parent_id, name, family, norm, grouping, matrix_class, matrix_class_label, priority, scope_preliminary, scope_limits, tst_compatibility, modality, evidence_required, technical_responsibility, legal_reference, official_url, docs_received, rt_confirmed, resources_confirmed, audita_notes, commercial_status, status_basis, status_reference, pricing_model, billing_unit_ref) values
('SST-001', 'servico', null, 'Consultoria recorrente de SST para pequenas empresas', 'Consultoria', null, null, 'B', 'B — Em verificação', 'Alta', 'Visitas, orientação, registros e acompanhamento; não substitui automaticamente SESMT dimensionado', 'Visitas, orientação, registros e acompanhamento; não substitui automaticamente SESMT dimensionado', null, null, 'Registro TST, escopo contratual, regime de prestação e NR-4', null, 'Portaria MTE 3.275/1989; NR-4', 'https://www.gov.br/trabalho-e-emprego/pt-br/assuntos/inspecao-do-trabalho/seguranca-e-saude-no-trabalho/sst-portarias/1989/portaria_3-275_atividades_do_tec-_seg.pdf/%40%40download/file', 'nao', 'nao', 'nao', 'PRETENDO OFERECER ESTE SERVIÇO', 'nao_liberado', 'Situação inicial conforme AUDDOC004 Rev.00 (08/10/2026): nenhum serviço liberado para comercialização.', 'AUDDOC004 Rev.00 — Matriz de Serviços', 'hora_tecnica', 'mensalidade / visitas'),
('SST-002', 'servico', null, 'Inspeções periódicas de SST', 'Consultoria', null, null, 'B', 'B — Em verificação', 'Alta', 'Inspeção, apontamentos e relatório; não equivale a laudo privativo', 'Inspeção, apontamentos e relatório; não equivale a laudo privativo', null, null, 'Registro TST, checklist, competência e metodologia', null, 'Portaria MTE 3.275/1989', 'https://www.gov.br/trabalho-e-emprego/pt-br/assuntos/inspecao-do-trabalho/seguranca-e-saude-no-trabalho/sst-portarias/1989/portaria_3-275_atividades_do_tec-_seg.pdf/%40%40download/file', 'nao', 'nao', 'nao', 'PRETENDO OFERECER ESTE SERVIÇO', 'nao_liberado', 'Situação inicial conforme AUDDOC004 Rev.00 (08/10/2026): nenhum serviço liberado para comercialização.', 'AUDDOC004 Rev.00 — Matriz de Serviços', 'hora_tecnica', 'mensalidade / visitas'),
('SST-003', 'servico', null, 'DDS, campanhas e conscientização de SST', 'Treinamento', null, null, 'B', 'B — Em verificação', 'Alta', 'Palestras e orientações; não substituir treinamentos obrigatórios quando exigidos', 'Palestras e orientações; não substituir treinamentos obrigatórios quando exigidos', null, null, 'Registro TST, experiência temática e material adequado', null, 'Portaria MTE 3.275/1989', 'https://www.gov.br/trabalho-e-emprego/pt-br/assuntos/inspecao-do-trabalho/seguranca-e-saude-no-trabalho/sst-portarias/1989/portaria_3-275_atividades_do_tec-_seg.pdf/%40%40download/file', 'nao', 'nao', 'nao', 'PRETENDO OFERECER ESTE SERVIÇO', 'nao_liberado', 'Situação inicial conforme AUDDOC004 Rev.00 (08/10/2026): nenhum serviço liberado para comercialização.', 'AUDDOC004 Rev.00 — Matriz de Serviços', 'hora_tecnica', 'turma / participante'),
('SST-004', 'servico', null, 'Apoio ao controle e entrega de EPIs', 'Consultoria', null, null, 'B', 'B — Em verificação', 'Alta', 'Gestão e registros de entrega, conservação e substituição; decisões conforme riscos', 'Gestão e registros de entrega, conservação e substituição; decisões conforme riscos', null, null, 'NR-6, métodos de registro e instruções do fabricante', null, 'NR-6', 'https://www.gov.br/trabalho-e-emprego/pt-br/assuntos/inspecao-do-trabalho/seguranca-e-saude-no-trabalho/ctpp-nrs/normas-regulamentadoras-nrs', 'nao', 'nao', 'nao', 'PRETENDO OFERECER ESTE SERVIÇO', 'nao_liberado', 'Situação inicial conforme AUDDOC004 Rev.00 (08/10/2026): nenhum serviço liberado para comercialização.', 'AUDDOC004 Rev.00 — Matriz de Serviços', 'hora_tecnica', 'mensalidade / visitas'),
('SST-005', 'servico', null, 'Ordens de serviço e procedimentos operacionais de SST', 'Documentos', null, null, 'B', 'B — Em verificação', 'Alta', 'Redação e acompanhamento de OS/procedimentos; excluir projetos/laudos especializados', 'Redação e acompanhamento de OS/procedimentos; excluir projetos/laudos especializados', null, null, 'Registro TST, escopo, riscos dos processos e validação do empregador', null, 'NR-1; Portaria MTE 3.275/1989', 'https://www.gov.br/trabalho-e-emprego/pt-br/acesso-a-informacao/participacao-social/conselhos-e-orgaos-colegiados/comissao-tripartite-partitaria-permanente/normas-regulamentadora/normas-regulamentadoras-vigentes/nr-1', 'nao', 'nao', 'nao', 'PRETENDO OFERECER ESTE SERVIÇO', 'nao_liberado', 'Situação inicial conforme AUDDOC004 Rev.00 (08/10/2026): nenhum serviço liberado para comercialização.', 'AUDDOC004 Rev.00 — Matriz de Serviços', 'hora_tecnica', 'entregável / unidade'),
('SST-006', 'servico', null, 'Organização administrativa das rotinas da CIPA', 'Consultoria', null, null, 'B', 'B — Em verificação', 'Alta', 'Agenda, atas, ações e acompanhamento; competências da comissão preservadas', 'Agenda, atas, ações e acompanhamento; competências da comissão preservadas', null, null, 'NR-5, processo eleitoral e treinamento conforme caso', null, 'NR-5', 'https://www.gov.br/trabalho-e-emprego/pt-br/assuntos/inspecao-do-trabalho/seguranca-e-saude-no-trabalho/ctpp-nrs/normas-regulamentadoras-nrs', 'nao', 'nao', 'nao', 'PRETENDO OFERECER ESTE SERVIÇO', 'nao_liberado', 'Situação inicial conforme AUDDOC004 Rev.00 (08/10/2026): nenhum serviço liberado para comercialização.', 'AUDDOC004 Rev.00 — Matriz de Serviços', 'hora_tecnica', 'mensalidade / visitas'),
('SST-007', 'servico', null, 'Apoio à organização da brigada de emergência', 'Consultoria', null, null, 'B', 'B — Em verificação', 'Alta', 'Controle de reuniões, documentos e exercícios; não emitir certificação de instrutor sem requisitos', 'Controle de reuniões, documentos e exercícios; não emitir certificação de instrutor sem requisitos', null, null, 'IT do Corpo de Bombeiros/SP, características da edificação e requisitos locais', null, 'NR-23 e instruções técnicas estaduais', 'https://www.gov.br/trabalho-e-emprego/pt-br/assuntos/inspecao-do-trabalho/seguranca-e-saude-no-trabalho/ctpp-nrs/normas-regulamentadoras-nrs', 'nao', 'nao', 'nao', 'PRETENDO OFERECER ESTE SERVIÇO', 'nao_liberado', 'Situação inicial conforme AUDDOC004 Rev.00 (08/10/2026): nenhum serviço liberado para comercialização.', 'AUDDOC004 Rev.00 — Matriz de Serviços', 'hora_tecnica', 'mensalidade / visitas'),
('SST-008', 'servico', null, 'Apoio ao acompanhamento de planos de emergência', 'Consultoria', null, null, 'B', 'B — Em verificação', 'Média', 'Organização, registros e simulados; projetos/assinaturas exigidos em casos específicos', 'Organização, registros e simulados; projetos/assinaturas exigidos em casos específicos', null, null, 'Norma local, escopo e profissional exigido por tipo de instalação', null, 'NR-23 e legislação estadual/local', 'https://www.gov.br/trabalho-e-emprego/pt-br/assuntos/inspecao-do-trabalho/seguranca-e-saude-no-trabalho/ctpp-nrs/normas-regulamentadoras-nrs', 'nao', 'nao', 'nao', 'PRETENDO OFERECER ESTE SERVIÇO', 'nao_liberado', 'Situação inicial conforme AUDDOC004 Rev.00 (08/10/2026): nenhum serviço liberado para comercialização.', 'AUDDOC004 Rev.00 — Matriz de Serviços', 'hora_tecnica', 'mensalidade / visitas'),
('SST-009', 'servico', null, 'Relatório técnico de inspeções e registro fotográfico', 'Documentos', null, null, 'B', 'B — Em verificação', 'Alta', 'Relatório de constatações, sem se apresentar como laudo de engenharia', 'Relatório de constatações, sem se apresentar como laudo de engenharia', null, null, 'Registro TST, metodologia e limitações da avaliação', null, 'Portaria MTE 3.275/1989', 'https://www.gov.br/trabalho-e-emprego/pt-br/assuntos/inspecao-do-trabalho/seguranca-e-saude-no-trabalho/sst-portarias/1989/portaria_3-275_atividades_do_tec-_seg.pdf/%40%40download/file', 'nao', 'nao', 'nao', 'PRETENDO OFERECER ESTE SERVIÇO', 'nao_liberado', 'Situação inicial conforme AUDDOC004 Rev.00 (08/10/2026): nenhum serviço liberado para comercialização.', 'AUDDOC004 Rev.00 — Matriz de Serviços', 'hora_tecnica', 'entregável / unidade'),
('SST-010', 'servico', null, 'Acompanhamento de indicadores e planos de ação', 'Consultoria', null, null, 'B', 'B — Em verificação', 'Alta', 'Consolidação e monitoramento dos controles e decisões da empresa', 'Consolidação e monitoramento dos controles e decisões da empresa', null, null, 'Método, acesso autorizado a dados, LGPD', null, 'NR-1; Portaria MTE 3.275/1989', 'https://www.gov.br/trabalho-e-emprego/pt-br/acesso-a-informacao/participacao-social/conselhos-e-orgaos-colegiados/comissao-tripartite-partitaria-permanente/normas-regulamentadora/normas-regulamentadoras-vigentes/nr-1', 'nao', 'nao', 'nao', 'PRETENDO OFERECER ESTE SERVIÇO', 'nao_liberado', 'Situação inicial conforme AUDDOC004 Rev.00 (08/10/2026): nenhum serviço liberado para comercialização.', 'AUDDOC004 Rev.00 — Matriz de Serviços', 'hora_tecnica', 'mensalidade / visitas'),
('DOC-001', 'servico', null, 'Apoio à estruturação e manutenção do PGR/GRO', 'Documentos', null, null, 'B', 'B — Em verificação', 'Alta', 'Inventário + plano de ação; responsabilidade da organização e exigências específicas', 'Inventário + plano de ação; responsabilidade da organização e exigências específicas', null, null, 'Registro TST, definição de escopo, recursos e necessidades de avaliações especializadas', null, 'NR-1/GRO/PGR', 'https://www.gov.br/trabalho-e-emprego/pt-br/assuntos/inspecao-do-trabalho/pgr/principal', 'nao', 'nao', 'nao', 'PRETENDO OFERECER ESTE SERVIÇO', 'nao_liberado', 'Situação inicial conforme AUDDOC004 Rev.00 (08/10/2026): nenhum serviço liberado para comercialização.', 'AUDDOC004 Rev.00 — Matriz de Serviços', 'hora_tecnica', 'entregável / unidade'),
('DOC-002', 'servico', null, 'APR — Análise Preliminar de Riscos', 'Documentos', null, null, 'B', 'B — Em verificação', 'Alta', 'Documento de análise de tarefa/atividade; responsabilidade específica quando exigida', 'Documento de análise de tarefa/atividade; responsabilidade específica quando exigida', null, null, 'Metodologia, riscos, atividades e requisitos da tarefa', null, 'NR-1 + requisitos setoriais', 'https://www.gov.br/trabalho-e-emprego/pt-br/acesso-a-informacao/participacao-social/conselhos-e-orgaos-colegiados/comissao-tripartite-partitaria-permanente/normas-regulamentadora/normas-regulamentadoras-vigentes/nr-1', 'nao', 'nao', 'nao', 'PRETENDO OFERECER ESTE SERVIÇO', 'nao_liberado', 'Situação inicial conforme AUDDOC004 Rev.00 (08/10/2026): nenhum serviço liberado para comercialização.', 'AUDDOC004 Rev.00 — Matriz de Serviços', 'hora_tecnica', 'entregável / unidade'),
('DOC-003', 'servico', null, 'Avaliação ergonômica preliminar — triagem', 'Documentos', null, null, 'B', 'B — Em verificação', 'Média', 'Distinguir levantamento preliminar de AET aprofundada', 'Distinguir levantamento preliminar de AET aprofundada', null, null, 'Competência em ergonomia, escopo, método, requisitos NR-17', null, 'NR-17', 'https://www.gov.br/trabalho-e-emprego/pt-br/acesso-a-informacao/participacao-social/conselhos-e-orgaos-colegiados/comissao-tripartite-partitaria-permanente/normas-regulamentadora/normas-regulamentadoras-vigentes/nr-17-atualizada-2023.pdf', 'nao', 'nao', 'nao', 'PRETENDO OFERECER ESTE SERVIÇO', 'nao_liberado', 'Situação inicial conforme AUDDOC004 Rev.00 (08/10/2026): nenhum serviço liberado para comercialização.', 'AUDDOC004 Rev.00 — Matriz de Serviços', 'hora_tecnica', 'entregável / unidade'),
('TRN-001', 'servico', null, 'Integração e orientações introdutórias de SST', 'Treinamento', null, null, 'B', 'B — Em verificação', 'Alta', 'Treinamento de integração; comprovar conteúdos e requisitos do contexto', 'Treinamento de integração; comprovar conteúdos e requisitos do contexto', null, null, 'Qualificação instrutor, plano de aula, carga horária, modalidade', null, 'NR-1 e NR da atividade', 'https://www.gov.br/trabalho-e-emprego/pt-br/acesso-a-informacao/participacao-social/conselhos-e-orgaos-colegiados/comissao-tripartite-partitaria-permanente/normas-regulamentadora/normas-regulamentadoras-vigentes/nr-1', 'nao', 'nao', 'nao', 'PRETENDO OFERECER ESTE SERVIÇO', 'nao_liberado', 'Situação inicial conforme AUDDOC004 Rev.00 (08/10/2026): nenhum serviço liberado para comercialização.', 'AUDDOC004 Rev.00 — Matriz de Serviços', 'hora_tecnica', 'turma / participante'),
('TRN-002', 'servico', null, 'Orientação e treinamento sobre uso de EPI (NR-6)', 'Treinamento', null, null, 'B', 'B — Em verificação', 'Alta', 'Conteúdo, público e duração compatíveis com riscos/EPIs; sem promessa genérica de certificado NR', 'Conteúdo, público e duração compatíveis com riscos/EPIs; sem promessa genérica de certificado NR', null, null, 'Qualificação do instrutor, conteúdo, registros e instruções do fabricante', null, 'NR-6; NR-1', 'https://www.gov.br/trabalho-e-emprego/pt-br/assuntos/inspecao-do-trabalho/seguranca-e-saude-no-trabalho/ctpp-nrs/normas-regulamentadoras-nrs', 'nao', 'nao', 'nao', 'PRETENDO OFERECER ESTE SERVIÇO', 'nao_liberado', 'Situação inicial conforme AUDDOC004 Rev.00 (08/10/2026): nenhum serviço liberado para comercialização.', 'AUDDOC004 Rev.00 — Matriz de Serviços', 'hora_tecnica', 'turma / participante'),
('TRN-003', 'servico', null, 'Treinamento de CIPA (NR-5)', 'Treinamento', null, null, 'B', 'B — Em verificação', 'Média', 'Verificar conteúdo, modalidade e requisitos da empresa', 'Verificar conteúdo, modalidade e requisitos da empresa', null, null, 'NR-5, material, qualificação e carga horária aplicável', null, 'NR-5; NR-1', 'https://www.gov.br/trabalho-e-emprego/pt-br/assuntos/inspecao-do-trabalho/seguranca-e-saude-no-trabalho/ctpp-nrs/normas-regulamentadoras-nrs', 'nao', 'nao', 'nao', 'PRETENDO OFERECER ESTE SERVIÇO', 'nao_liberado', 'Situação inicial conforme AUDDOC004 Rev.00 (08/10/2026): nenhum serviço liberado para comercialização.', 'AUDDOC004 Rev.00 — Matriz de Serviços', 'hora_tecnica', 'turma / participante'),
('TRN-004', 'servico', null, 'Treinamentos de brigada e combate a incêndios', 'Treinamento', null, null, 'B', 'B — Em verificação', 'Média', 'Verificar regras estaduais, credenciamento e treinamento prático', 'Verificar regras estaduais, credenciamento e treinamento prático', null, null, 'Requisitos CB/SP, instalações, instrutores e recursos práticos', null, 'NR-23; IT estaduais', 'https://www.gov.br/trabalho-e-emprego/pt-br/assuntos/inspecao-do-trabalho/seguranca-e-saude-no-trabalho/ctpp-nrs/normas-regulamentadoras-nrs', 'nao', 'nao', 'nao', 'PRETENDO OFERECER ESTE SERVIÇO', 'nao_liberado', 'Situação inicial conforme AUDDOC004 Rev.00 (08/10/2026): nenhum serviço liberado para comercialização.', 'AUDDOC004 Rev.00 — Matriz de Serviços', 'hora_tecnica', 'turma / participante'),
('TRN-005', 'servico', null, 'Treinamentos por NR — portfólio específico de 12 ofertas (aba Treinamentos por NR)', 'Treinamento', null, null, 'B', 'B — Em verificação', 'Média', 'Criar uma ficha separada para cada NR e tópico', 'Criar uma ficha separada para cada NR e tópico', null, null, 'Verificar requisitos por treinamento; 12 linhas específicas, com NR-11 empilhadeira e ponte rolante; NR-20 Básico; NR-17 unificado; NR-26 em dois temas.', null, 'NR-1 Anexo II + NR específica', 'https://www.gov.br/trabalho-e-emprego/pt-br/acesso-a-informacao/participacao-social/conselhos-e-orgaos-colegiados/comissao-tripartite-partitaria-permanente/normas-regulamentadora/normas-regulamentadoras-vigentes/NR01atualizada2024I.pdf', 'nao', 'nao', 'nao', 'INTERESSE CONFIRMADO nas 12 ofertas; proficiência do instrutor declarada pelo responsável, comprovação/recursos e liberação por curso pendentes.', 'nao_liberado', 'Situação inicial conforme AUDDOC004 Rev.00 (08/10/2026): nenhum serviço liberado para comercialização.', 'AUDDOC004 Rev.00 — Matriz de Serviços', 'hora_tecnica', 'turma / participante'),
('AUD-001', 'servico', null, 'Auditoria interna de SST / conformidade de NR', 'Auditoria', null, null, 'B', 'B — Em verificação', 'Alta', 'Auditoria independente do processo auditado; não é certificação acreditada', 'Auditoria independente do processo auditado; não é certificação acreditada', null, null, 'Competência no critério, checklists, independência e escopo', null, 'NRs aplicáveis; Portaria MTE 3.275/1989', 'https://www.gov.br/trabalho-e-emprego/pt-br/assuntos/inspecao-do-trabalho/seguranca-e-saude-no-trabalho/sst-portarias/1989/portaria_3-275_atividades_do_tec-_seg.pdf/%40%40download/file', 'nao', 'nao', 'nao', 'PRETENDO OFERECER ESTE SERVIÇO | Certificado Bureau Veritas 24 h de interpretação e implementação ISO 9001/14001/45001 recebido; certificado de auditoria interna pendente.', 'nao_liberado', 'Situação inicial conforme AUDDOC004 Rev.00 (08/10/2026): nenhum serviço liberado para comercialização.', 'AUDDOC004 Rev.00 — Matriz de Serviços', 'hora_tecnica', 'dia / hora técnica'),
('AUD-002', 'servico', null, 'Auditoria interna de SGI (ISO 9001/14001/45001)', 'Auditoria', null, null, 'B', 'B — Em verificação', 'Média', 'Verificar competência técnica, critérios e independência da auditoria', 'Verificar competência técnica, critérios e independência da auditoria', null, null, 'Comprovação de curso de auditoria interna e experiência; certificado de interpretação/implementação das 3 ISO apresentado; competência e independência verificadas por escopo.', null, 'Normas de SGI + competência do auditor', 'https://www.gov.br/inmetro/pt-br/assuntos/acreditacao-reconhecimento-bpl/cgcre/acreditacao', 'parcial', 'nao', 'nao', 'PRETENDO OFERECER ESTE SERVIÇO | Certificado Bureau Veritas 24 h de interpretação e implementação ISO 9001/14001/45001 recebido; certificado de auditoria interna pendente.', 'nao_liberado', 'Situação inicial conforme AUDDOC004 Rev.00 (08/10/2026): nenhum serviço liberado para comercialização.', 'AUDDOC004 Rev.00 — Matriz de Serviços', 'hora_tecnica', 'dia / hora técnica'),
('AUD-003', 'servico', null, 'Auditorias de fornecedores (segunda parte)', 'Auditoria', null, null, 'B', 'B — Em verificação', 'Média', 'Serviço a terceiros; não declarar certificação de terceira parte', 'Serviço a terceiros; não declarar certificação de terceira parte', null, null, 'Contrato, escopo, competência e imparcialidade adequada', null, 'Critérios contratuais / sistema de gestão', 'https://www.gov.br/inmetro/pt-br/assuntos/acreditacao-reconhecimento-bpl/cgcre/acreditacao', 'nao', 'nao', 'nao', 'PRETENDO OFERECER ESTE SERVIÇO | Certificado Bureau Veritas 24 h de interpretação e implementação ISO 9001/14001/45001 recebido; certificado de auditoria interna pendente.', 'nao_liberado', 'Situação inicial conforme AUDDOC004 Rev.00 (08/10/2026): nenhum serviço liberado para comercialização.', 'AUDDOC004 Rev.00 — Matriz de Serviços', 'hora_tecnica', 'dia / hora técnica'),
('AUD-004', 'servico', null, 'Diagnóstico preparatório para certificação SGI', 'Auditoria', null, null, 'B', 'B — Em verificação', 'Média', 'Diagnóstico/consultoria, não certificação acreditada', 'Diagnóstico/consultoria, não certificação acreditada', null, null, 'Competência e normas aplicáveis; delimitar linguagem comercial', null, 'Normas de SGI aplicáveis', 'https://www.gov.br/inmetro/pt-br/assuntos/acreditacao-reconhecimento-bpl/cgcre/acreditacao', 'nao', 'nao', 'nao', 'PRETENDO OFERECER ESTE SERVIÇO | Certificado Bureau Veritas 24 h de interpretação e implementação ISO 9001/14001/45001 recebido; certificado de auditoria interna pendente.', 'nao_liberado', 'Situação inicial conforme AUDDOC004 Rev.00 (08/10/2026): nenhum serviço liberado para comercialização.', 'AUDDOC004 Rev.00 — Matriz de Serviços', 'hora_tecnica', 'dia / hora técnica'),
('AMB-001', 'servico', null, 'Controle documental ambiental e gestão de vencimentos', 'Meio Ambiente', null, null, 'B', 'B — Em verificação', 'Média', 'Gestão administrativa; análises/assinaturas especializadas quando cabíveis', 'Gestão administrativa; análises/assinaturas especializadas quando cabíveis', null, null, 'Escopo, autorizações, legislação e competências', null, 'Portaria MTE 3.275/1989 + legislação ambiental aplicável', 'https://www.gov.br/trabalho-e-emprego/pt-br/assuntos/inspecao-do-trabalho/seguranca-e-saude-no-trabalho/sst-portarias/1989/portaria_3-275_atividades_do_tec-_seg.pdf/%40%40download/file', 'nao', 'nao', 'nao', 'PRETENDO OFERECER ESTE SERVIÇO', 'nao_liberado', 'Situação inicial conforme AUDDOC004 Rev.00 (08/10/2026): nenhum serviço liberado para comercialização.', 'AUDDOC004 Rev.00 — Matriz de Serviços', 'hora_tecnica', 'serviço / rotina'),
('AMB-002', 'servico', null, 'Apoio a registros de resíduos e rotinas ambientais', 'Meio Ambiente', null, null, 'B', 'B — Em verificação', 'Média', 'Apoio administrativo/operacional, sem substituir responsável técnico especializado', 'Apoio administrativo/operacional, sem substituir responsável técnico especializado', null, null, 'Regras estaduais, tipos de resíduos e atribuições profissionais', null, 'Legislação federal/estadual conforme serviço', 'https://www.gov.br/trabalho-e-emprego/pt-br/assuntos/inspecao-do-trabalho/seguranca-e-saude-no-trabalho/sst-portarias/1989/portaria_3-275_atividades_do_tec-_seg.pdf/%40%40download/file', 'nao', 'nao', 'nao', 'PRETENDO OFERECER ESTE SERVIÇO', 'nao_liberado', 'Situação inicial conforme AUDDOC004 Rev.00 (08/10/2026): nenhum serviço liberado para comercialização.', 'AUDDOC004 Rev.00 — Matriz de Serviços', 'hora_tecnica', 'serviço / rotina'),
('SIS-001', 'servico', null, 'Assinatura do Audita HUB', 'Software', null, null, 'B', 'B — Em verificação', 'Alta', 'Licenciamento da plataforma; não equivale a prestação de responsabilidade técnica', 'Licenciamento da plataforma; não equivale a prestação de responsabilidade técnica', null, null, 'Produto homologado, LGPD, suporte, termos e contratos', null, 'Requisitos contratuais, LGPD e escopo técnico', 'https://www.gov.br/trabalho-e-emprego/pt-br/assuntos/inspecao-do-trabalho/pgr/principal', 'nao', 'nao', 'nao', 'PRETENDO OFERECER ESTE SERVIÇO', 'nao_liberado', 'Situação inicial conforme AUDDOC004 Rev.00 (08/10/2026): nenhum serviço liberado para comercialização.', 'AUDDOC004 Rev.00 — Matriz de Serviços', 'sem_modelo_definido', 'plano / mês (modelo SaaS a definir — AUDDOC011 §6)'),
('SIS-002', 'servico', null, 'Audita PRO — uso na prestação de serviços', 'Software', null, null, 'B', 'B — Em verificação', 'Alta', 'Plataforma de operação; certificação não é presumida pelo sistema', 'Plataforma de operação; certificação não é presumida pelo sistema', null, null, 'Produto homologado, RLS, segurança, rastreabilidade e contratos', null, 'Controle documental e requisitos de auditoria', 'https://www.gov.br/inmetro/pt-br/assuntos/acreditacao-reconhecimento-bpl/cgcre/acreditacao', 'nao', 'nao', 'nao', 'PRETENDO OFERECER ESTE SERVIÇO', 'nao_liberado', 'Situação inicial conforme AUDDOC004 Rev.00 (08/10/2026): nenhum serviço liberado para comercialização.', 'AUDDOC004 Rev.00 — Matriz de Serviços', 'sem_modelo_definido', null),
('ESP-001', 'servico', null, 'LTCAT — emissão do laudo', 'Laudo especializado', null, null, 'C', 'C — Expansão futura', 'Futura', 'Parceiro legalmente habilitado; assinatura/responsabilidade técnica', 'Exigência legal de médico do trabalho ou engenheiro de segurança do trabalho', null, null, 'Parceiro legalmente habilitado; assinatura/responsabilidade técnica', null, 'Lei 8.213/1991, art. 58', 'https://www.planalto.gov.br/ccivil_03/leis/l8213compilado.htm', 'nao', 'nao', 'nao', 'PRETENDO OFERECER ESTE SERVIÇO', 'nao_liberado', 'Situação inicial conforme AUDDOC004 Rev.00 (08/10/2026): nenhum serviço liberado para comercialização.', 'AUDDOC004 Rev.00 — Matriz de Serviços', 'hora_tecnica', null),
('ESP-002', 'servico', null, 'Laudo de insalubridade', 'Laudo especializado', null, null, 'C', 'C — Expansão futura', 'Futura', 'Médico/engenheiro habilitado conforme enquadramento e documentação', 'Exige profissional competente segundo legislação', null, null, 'Médico/engenheiro habilitado conforme enquadramento e documentação', null, 'CLT art. 195; NR-15', 'https://www.planalto.gov.br/ccivil_03/decreto-lei/del5452.htm', 'nao', 'nao', 'nao', 'PRETENDO OFERECER ESTE SERVIÇO', 'nao_liberado', 'Situação inicial conforme AUDDOC004 Rev.00 (08/10/2026): nenhum serviço liberado para comercialização.', 'AUDDOC004 Rev.00 — Matriz de Serviços', 'hora_tecnica', null),
('ESP-003', 'servico', null, 'Laudo de periculosidade', 'Laudo especializado', null, null, 'C', 'C — Expansão futura', 'Futura', 'Médico/engenheiro habilitado conforme enquadramento e documentação', 'Exige profissional competente segundo legislação', null, null, 'Médico/engenheiro habilitado conforme enquadramento e documentação', null, 'CLT art. 195; NR-16', 'https://www.planalto.gov.br/ccivil_03/decreto-lei/del5452.htm', 'nao', 'nao', 'nao', 'PRETENDO OFERECER ESTE SERVIÇO', 'nao_liberado', 'Situação inicial conforme AUDDOC004 Rev.00 (08/10/2026): nenhum serviço liberado para comercialização.', 'AUDDOC004 Rev.00 — Matriz de Serviços', 'hora_tecnica', null),
('ESP-004', 'servico', null, 'PCMSO e avaliações médicas ocupacionais', 'Saúde ocupacional', null, null, 'C', 'C — Expansão futura', 'Futura', 'Parceria médica; procedimentos e responsabilidade próprios', 'Requer médico responsável nos termos aplicáveis', null, null, 'Parceria médica; procedimentos e responsabilidade próprios', null, 'NR-7', 'https://www.gov.br/trabalho-e-emprego/pt-br/assuntos/inspecao-do-trabalho/seguranca-e-saude-no-trabalho/ctpp-nrs/normas-regulamentadoras-nrs', 'nao', 'nao', 'nao', 'PRETENDO OFERECER ESTE SERVIÇO', 'nao_liberado', 'Situação inicial conforme AUDDOC004 Rev.00 (08/10/2026): nenhum serviço liberado para comercialização.', 'AUDDOC004 Rev.00 — Matriz de Serviços', 'hora_tecnica', null),
('ESP-005', 'servico', null, 'AET aprofundada e laudos ergonômicos especializados', 'Laudo especializado', null, null, 'C', 'C — Expansão futura', 'Futura', 'Profissional competente, método e meios técnicos', 'Diferenciar da triagem; requer expertise suficiente e escopo técnico próprio', null, null, 'Profissional competente, método e meios técnicos', null, 'NR-17', 'https://www.gov.br/trabalho-e-emprego/pt-br/acesso-a-informacao/participacao-social/conselhos-e-orgaos-colegiados/comissao-tripartite-partitaria-permanente/normas-regulamentadora/normas-regulamentadoras-vigentes/nr-17-atualizada-2023.pdf', 'nao', 'nao', 'nao', 'PRETENDO OFERECER ESTE SERVIÇO', 'nao_liberado', 'Situação inicial conforme AUDDOC004 Rev.00 (08/10/2026): nenhum serviço liberado para comercialização.', 'AUDDOC004 Rev.00 — Matriz de Serviços', 'hora_tecnica', null),
('ESP-006', 'servico', null, 'Laudos e projetos de engenharia (ex.: máquinas/NR-12)', 'Laudo especializado', null, null, 'C', 'C — Expansão futura', 'Futura', 'Engenheiro habilitado, CREA/ART e recursos', 'Projeto/laudo técnico de engenharia ou ART quando cabível', null, null, 'Engenheiro habilitado, CREA/ART e recursos', null, 'NR-12 + atribuições de engenharia', 'https://www.gov.br/trabalho-e-emprego/pt-br/assuntos/inspecao-do-trabalho/seguranca-e-saude-no-trabalho/ctpp-nrs/normas-regulamentadoras-nrs', 'nao', 'nao', 'nao', 'PRETENDO OFERECER ESTE SERVIÇO', 'nao_liberado', 'Situação inicial conforme AUDDOC004 Rev.00 (08/10/2026): nenhum serviço liberado para comercialização.', 'AUDDOC004 Rev.00 — Matriz de Serviços', 'hora_tecnica', null),
('ESP-007', 'servico', null, 'Certificação acreditada de sistemas de gestão (terceira parte)', 'Certificação', null, null, 'C', 'C — Expansão futura', 'Futura', 'Requisitos organismo certificador, ABNT NBR ISO/IEC 17021-1 e Cgcre', 'Estrutura organizacional, competência, imparcialidade e acreditação próprias', null, null, 'Requisitos organismo certificador, ABNT NBR ISO/IEC 17021-1 e Cgcre', null, 'Inmetro Cgcre; ISO/IEC 17021-1', 'https://www.gov.br/inmetro/pt-br/assuntos/acreditacao-reconhecimento-bpl/cgcre/acreditacao', 'nao', 'nao', 'nao', 'PRETENDO OFERECER ESTE SERVIÇO', 'nao_liberado', 'Situação inicial conforme AUDDOC004 Rev.00 (08/10/2026): nenhum serviço liberado para comercialização.', 'AUDDOC004 Rev.00 — Matriz de Serviços', 'hora_tecnica', null);

insert into audita.services (service_code, kind, parent_id, name, family, norm, grouping, matrix_class, matrix_class_label, priority, scope_preliminary, scope_limits, tst_compatibility, modality, evidence_required, technical_responsibility, legal_reference, official_url, docs_received, rt_confirmed, resources_confirmed, audita_notes, commercial_status, status_basis, status_reference, pricing_model, billing_unit_ref) values
('TRN-NR01', 'oferta', (select id from audita.services where service_code = 'TRN-005'), 'Integração de SST e orientação sobre riscos específicos do cliente', 'Treinamento', 'NR-01', 'Integração e orientação', 'B', 'B — Em verificação', null, 'In loco ou EAD apenas se permitido para conteúdos aplicáveis', 'Não vender certificado ''NR-01'' genérico como substituto de capacitação de NR específica', 'Compatibilidade inicial com atribuições TST; escopo deve ser delimitado', 'In loco ou EAD apenas se permitido para conteúdos aplicáveis', 'Proficiência como instrutor declarada; organizar comprovação, programa, objetivos, avaliação e recursos exigidos.', 'Verificar NR-01/caso; ART não presumida', 'NR-01', 'https://www.gov.br/trabalho-e-emprego/pt-br/assuntos/inspecao-do-trabalho/seguranca-e-saude-no-trabalho/ctpp-nrs/normas-regulamentadoras-nrs', 'nao', 'nao', 'nao', 'Classificar como integração/orientação, não curso universal obrigatório | Declaração de proficiência registrada; documentação própria ainda será produzida.', 'nao_liberado', 'Situação inicial conforme AUDDOC004 Rev.00 (08/10/2026): nenhum serviço liberado para comercialização.', 'AUDDOC004 Rev.00 — Treinamentos por NR', 'hora_tecnica', 'turma / participante'),
('TRN-NR06', 'oferta', (select id from audita.services where service_code = 'TRN-005'), 'Uso, ajuste, guarda e conservação de EPIs', 'Treinamento', 'NR-06', 'EPI', 'B', 'B — Em verificação', null, 'Priorizar presencial quando houver demonstração prática', 'Instruções do fabricante, CA, riscos, atividades e treinamento específico quando requerido', 'Compatibilidade inicial com atuação em SST; demonstrar domínio do EPI específico', 'Priorizar presencial quando houver demonstração prática', 'Proficiência como instrutor declarada; organizar comprovação, programa, objetivos, avaliação e recursos exigidos.', 'Verificar requisitos; ART não presumida', 'NR-06; NR-01', 'https://www.gov.br/trabalho-e-emprego/pt-br/assuntos/inspecao-do-trabalho/seguranca-e-saude-no-trabalho/ctpp-nrs/normas-regulamentadoras-nrs', 'nao', 'nao', 'nao', 'Escopo por tipos de EPI | Declaração de proficiência registrada; documentação própria ainda será produzida.', 'nao_liberado', 'Situação inicial conforme AUDDOC004 Rev.00 (08/10/2026): nenhum serviço liberado para comercialização.', 'AUDDOC004 Rev.00 — Treinamentos por NR', 'hora_tecnica', 'turma / participante'),
('TRN-NR05', 'oferta', (select id from audita.services where service_code = 'TRN-005'), 'Capacitação de CIPA e representante nomeado', 'Treinamento', 'NR-05', 'CIPA', 'B', 'B — Em verificação', null, 'Presencial/EAD/híbrido conforme NR-01, NR-05 e projeto pedagógico', 'Conteúdo, carga horária, grau de risco, prevenção de assédio e particularidades', 'Potencialmente compatível, desde que requisitos normativos cumpridos', 'Presencial/EAD/híbrido conforme NR-01, NR-05 e projeto pedagógico', 'Proficiência como instrutor declarada; organizar comprovação, programa, objetivos, avaliação e recursos exigidos.', 'Verificar responsável técnico conforme NR-01; ART não presumida', 'NR-05; NR-01', 'https://www.gov.br/trabalho-e-emprego/pt-br/acesso-a-informacao/participacao-social/conselhos-e-orgaos-colegiados/comissao-tripartite-partitaria-permanente/normas-regulamentadora/normas-regulamentadoras-vigentes/norma-regulamentadora-no-5-nr-5', 'nao', 'nao', 'nao', 'Confirmar enquadramento do estabelecimento | Declaração de proficiência registrada; documentação própria ainda será produzida.', 'nao_liberado', 'Situação inicial conforme AUDDOC004 Rev.00 (08/10/2026): nenhum serviço liberado para comercialização.', 'AUDDOC004 Rev.00 — Treinamentos por NR', 'hora_tecnica', 'turma / participante'),
('TRN-NR11-E', 'oferta', (select id from audita.services where service_code = 'TRN-005'), 'NR-11 — Operação segura de empilhadeira', 'Treinamento', 'NR-11', 'Operação de empilhadeira', 'B', 'B — Em verificação', null, 'Preferencialmente presencial, com uso seguro de empilhadeira, prática e avaliação no equipamento correspondente', 'Capacitação específica, operador, tipo/modelo, fabricante e riscos locais; confirmar requisitos NR-11 e outras NRs aplicáveis', 'Proficiência como instrutor DECLARADA; demonstrar experiência específica com empilhadeira', 'Preferencialmente presencial, com uso seguro de empilhadeira, prática e avaliação no equipamento correspondente', 'Evidências de experiência e proficiência no equipamento + plano, avaliação prática e disponibilização de empilhadeira e área segura', 'ART não presumida; conferir obrigações do cliente, do equipamento e eventual responsável', 'NR-11', 'https://www.gov.br/trabalho-e-emprego/pt-br/acesso-a-informacao/participacao-social/conselhos-e-orgaos-colegiados/comissao-tripartite-partitaria-permanente/normas-regulamentadora/normas-regulamentadoras-vigentes/norma-regulamentadora-no-11-nr-11', 'nao', 'nao', 'nao', 'Desdobramento solicitado; não equiparar conhecimento geral de SST à habilidade operacional. Experiência/proficiência declaradas, comprovação a organizar.', 'nao_liberado', 'Situação inicial conforme AUDDOC004 Rev.00 (08/10/2026): nenhum serviço liberado para comercialização.', 'AUDDOC004 Rev.00 — Treinamentos por NR', 'hora_tecnica', 'turma / participante'),
('TRN-NR11-P', 'oferta', (select id from audita.services where service_code = 'TRN-005'), 'NR-11 — Operação segura de ponte rolante', 'Treinamento', 'NR-11', 'Operação de ponte rolante', 'B', 'B — Em verificação', null, 'Presencial com atividades e avaliação práticas no equipamento/instalação compatíveis', 'Capacitação específica, tipos de carga, sinalização, içamento, acessórios e riscos locais; confirmar requisitos aplicáveis', 'Proficiência como instrutor DECLARADA; demonstrar experiência específica com ponte rolante', 'Presencial com atividades e avaliação práticas no equipamento/instalação compatíveis', 'Experiência e proficiência no equipamento + recursos de prática e avaliação no local', 'ART não presumida; conferir obrigações do cliente, do equipamento e eventual responsável', 'NR-11', 'https://www.gov.br/trabalho-e-emprego/pt-br/acesso-a-informacao/participacao-social/conselhos-e-orgaos-colegiados/comissao-tripartite-partitaria-permanente/normas-regulamentadora/normas-regulamentadoras-vigentes/norma-regulamentadora-no-11-nr-11', 'nao', 'nao', 'nao', 'Curso distinto do treinamento de empilhadeira; verificar interface com demais NRs e procedimentos do empregador.', 'nao_liberado', 'Situação inicial conforme AUDDOC004 Rev.00 (08/10/2026): nenhum serviço liberado para comercialização.', 'AUDDOC004 Rev.00 — Treinamentos por NR', 'hora_tecnica', 'turma / participante'),
('TRN-NR17', 'oferta', (select id from audita.services where service_code = 'TRN-005'), 'NR-17 — Ergonomia e prevenção de riscos ergonômicos', 'Treinamento', 'NR-17', 'Orientações e capacitação por processo/função', 'B', 'B — Em verificação', null, 'Presencial ou EAD quando pertinente e permitido', 'Exigências de anexos e atividades; não se confunde com laudo AET', 'Orientação preventiva inicial compatível; conteúdo especializado depende de competência', 'Presencial ou EAD quando pertinente e permitido', 'Programa por atividade, materiais, experiência', 'Verificar NR/caso; ART não presumida', 'NR-17', 'https://www.gov.br/trabalho-e-emprego/pt-br/acesso-a-informacao/participacao-social/conselhos-e-orgaos-colegiados/comissao-tripartite-partitaria-permanente/normas-regulamentadora/normas-regulamentadoras-vigentes/norma-regulamentadora-no-17-nr-17', 'nao', 'nao', 'nao', 'ÚNICO curso de NR-17 na matriz, conforme solicitação; não implica emissão de AET/laudo especializado.', 'nao_liberado', 'Situação inicial conforme AUDDOC004 Rev.00 (08/10/2026): nenhum serviço liberado para comercialização.', 'AUDDOC004 Rev.00 — Treinamentos por NR', 'hora_tecnica', 'turma / participante'),
('TRN-NR20', 'oferta', (select id from audita.services where service_code = 'TRN-005'), 'NR-20 — Curso Básico: segurança com inflamáveis e combustíveis', 'Treinamento', 'NR-20', 'Curso Básico — atividade e classe da instalação', 'B', 'B — Em verificação', null, 'Parte teórica e prática sobre sistemas de segurança contra incêndio com inflamáveis existentes na instalação; EAD só para parte autorizada', 'Verificar enquadramento de instalação e função na Tabela 1 do Anexo I e respectiva carga horária; não é curso genérico para todos produtos químicos', 'Instrutor com proficiência DECLARADA; NR-20 exige proficiência e responsável pela organização técnica, um dos instrutores', 'Parte teórica e prática sobre sistemas de segurança contra incêndio com inflamáveis existentes na instalação; EAD só para parte autorizada', 'Proficiência declarada (evidências a organizar), programa e carga horária conforme enquadramento, estrutura prática e responsável pela organização técnica', 'Para Curso Básico, responsável pela organização técnica deve ser um dos instrutores; ART não é exigência genérica do curso.', 'NR-20 20.12.3/20.12.3.1/20.12.10/20.12.11; Anexo I', 'https://www.gov.br/trabalho-e-emprego/pt-br/acesso-a-informacao/participacao-social/conselhos-e-orgaos-colegiados/comissao-tripartite-partitaria-permanente/arquivos/normas-regulamentadoras/nr-20-atualizada-2022-1.pdf/%40%40download/file', 'nao', 'nao', 'nao', 'Oferta limitada ao Curso Básico. A marcação “produtos químicos” exige verificar se há inflamáveis/combustíveis na NR-20. NR-26/FDS é uma oferta distinta.', 'nao_liberado', 'Situação inicial conforme AUDDOC004 Rev.00 (08/10/2026): nenhum serviço liberado para comercialização.', 'AUDDOC004 Rev.00 — Treinamentos por NR', 'hora_tecnica', 'turma / participante'),
('TRN-NR26A', 'oferta', (select id from audita.services where service_code = 'TRN-005'), 'Sinalização de segurança', 'Treinamento', 'NR-26', 'Sinalização', 'B', 'B — Em verificação', null, 'Presencial ou EAD quando adequado', 'Determinar se capacitação específica é requerida ou é orientação de apoio', 'Orientações preventivas potencialmente compatíveis', 'Presencial ou EAD quando adequado', 'Proficiência como instrutor declarada; organizar comprovação, programa, objetivos, avaliação e recursos exigidos.', 'Verificar caso; ART não presumida', 'NR-26', 'https://www.gov.br/trabalho-e-emprego/pt-br/assuntos/inspecao-do-trabalho/seguranca-e-saude-no-trabalho/ctpp-nrs/normas-regulamentadoras-nrs', 'nao', 'nao', 'nao', 'Não declarar certificado obrigatório genérico | Declaração de proficiência registrada; documentação própria ainda será produzida.', 'nao_liberado', 'Situação inicial conforme AUDDOC004 Rev.00 (08/10/2026): nenhum serviço liberado para comercialização.', 'AUDDOC004 Rev.00 — Treinamentos por NR', 'hora_tecnica', 'turma / participante'),
('TRN-NR26B', 'oferta', (select id from audita.services where service_code = 'TRN-005'), 'Produtos químicos: rotulagem preventiva e FDS', 'Treinamento', 'NR-26', 'Produtos químicos', 'B', 'B — Em verificação', null, 'Preferir in loco com exemplos dos produtos do cliente', 'Reconhecimento de perigos, FDS vigente, GHS e riscos reais', 'Orientação preventiva potencialmente compatível, com proficiência química específica', 'Preferir in loco com exemplos dos produtos do cliente', 'Proficiência como instrutor declarada; organizar comprovação, programa, objetivos, avaliação e recursos exigidos.', 'Verificar caso; ART não presumida', 'NR-26', 'https://www.gov.br/trabalho-e-emprego/pt-br/assuntos/inspecao-do-trabalho/seguranca-e-saude-no-trabalho/ctpp-nrs/normas-regulamentadoras-nrs', 'nao', 'nao', 'nao', 'Possível ofertar separadamente do TRN-NR26A | Declaração de proficiência registrada; documentação própria ainda será produzida.', 'nao_liberado', 'Situação inicial conforme AUDDOC004 Rev.00 (08/10/2026): nenhum serviço liberado para comercialização.', 'AUDDOC004 Rev.00 — Treinamentos por NR', 'hora_tecnica', 'turma / participante'),
('TRN-NR23', 'oferta', (select id from audita.services where service_code = 'TRN-005'), 'Orientações de prevenção de incêndios e evacuação', 'Treinamento', 'NR-23', 'Prevenção de incêndios', 'B', 'B — Em verificação', null, 'Presencial recomendável para rotas e exercícios', 'Requisitos de SP para brigada e orientações legais conforme edificação', 'Orientações teóricas possíveis com competência; não equivalem a curso de brigadista', 'Presencial recomendável para rotas e exercícios', 'Proficiência como instrutor declarada; organizar comprovação, programa, objetivos, avaliação e recursos exigidos.', 'Brigada formal exige checagem estadual; ART não presumida', 'NR-23; CBPMESP', 'https://www.gov.br/trabalho-e-emprego/pt-br/assuntos/inspecao-do-trabalho/seguranca-e-saude-no-trabalho/ctpp-nrs/normas-regulamentadoras-nrs', 'nao', 'nao', 'nao', 'Separar orientação NR-23 de formação de brigadista | Declaração de proficiência registrada; documentação própria ainda será produzida.', 'nao_liberado', 'Situação inicial conforme AUDDOC004 Rev.00 (08/10/2026): nenhum serviço liberado para comercialização.', 'AUDDOC004 Rev.00 — Treinamentos por NR', 'hora_tecnica', 'turma / participante'),
('TRN-NR33', 'oferta', (select id from audita.services where service_code = 'TRN-005'), 'Segurança e saúde em espaços confinados — por público e função', 'Treinamento', 'NR-33', 'Espaço confinado', 'B', 'B — Condicionado (RT, estrutura e prática)', null, 'Presencial obrigatória para capacitações referidas na NR-33', 'RT formal, programa específico, treinamento presencial, avaliação teórica/prática, emergência', 'Proficiência como instrutor DECLARADA; exige designação por responsável técnico', 'Presencial obrigatória para capacitações referidas na NR-33', 'Comprovação de proficiência + designação por RT + estrutura para avaliação prática + equipamentos e procedimentos', 'Exige RT de espaços confinados; não equiparar TST ao RT sem avaliação', 'NR-33, 33.5.2–33.5.4', 'https://www.gov.br/trabalho-e-emprego/pt-br/acesso-a-informacao/participacao-social/conselhos-e-orgaos-colegiados/comissao-tripartite-partitaria-permanente/normas-regulamentadora/normas-regulamentadoras-vigentes/norma-regulamentadora-no-33-nr-33', 'nao', 'nao', 'nao', 'Proficiência declarada não substitui RT, instrutor designado nem os requisitos operacionais e presenciais da capacitação.', 'nao_liberado', 'Situação inicial conforme AUDDOC004 Rev.00 (08/10/2026): nenhum serviço liberado para comercialização.', 'AUDDOC004 Rev.00 — Treinamentos por NR', 'hora_tecnica', 'turma / participante'),
('TRN-NR35', 'oferta', (select id from audita.services where service_code = 'TRN-005'), 'Trabalho em altura — capacitação inicial, periódica ou eventual', 'Treinamento', 'NR-35', 'Trabalho em altura', 'B', 'B — Condicionado (presencial e estrutura)', null, 'Presencial obrigatória após atualização de 2026', 'Verificar se TST pode assumir responsabilidade no escopo concreto, infraestrutura, emergências e avaliação', 'Proficiência como instrutor DECLARADA; deverá ser sustentada por experiência/evidências', 'Presencial obrigatória após atualização de 2026', 'Proficiência, estrutura presencial, prática e simulado compatível, controle de resgate/segurança e registros', 'A ART não é requisito universal do curso; análise contextual', 'NR-35, Portaria MTE 1.259/2026', 'https://www.gov.br/trabalho-e-emprego/pt-br/noticias-e-conteudo/2026/setembro/trabalho-em-altura-veja-o-que-muda-nos-treinamentos-e-nas-escadas-fixas-verticais', 'nao', 'nao', 'nao', 'NR-35 presencial conforme mudança 2026; ART não presumida. Declaração de proficiência registrada, com documentação adicional pendente.', 'nao_liberado', 'Situação inicial conforme AUDDOC004 Rev.00 (08/10/2026): nenhum serviço liberado para comercialização.', 'AUDDOC004 Rev.00 — Treinamentos por NR', 'hora_tecnica', 'turma / participante');

notify pgrst, 'reload schema';
